### ISSUE TITLE
uniqueidentifier вызывает ошибку и columnstore 

### ISSUE THREAD

**Issue by zabavin** [YPermitin/SQLServerTools#23]
Ваш вариант 
CREATE PARTITION FUNCTION PF_MOVE_HELPER_6EF0EAB8825247C4B77DC310C90310B7 ([uniqueidentifier] (16)) AS RANGE RIGHT FOR VALUES (0);
Вот так работает 

CREATE PARTITION FUNCTION PF_MOVE_HELPER_6EF0EAB8825247C4B77DC310C90310B7 (uniqueidentifier ) AS RANGE RIGHT FOR VALUES ( '00000000-0000-0000-0000-000000000000');

**Comment by zabavin** [comment]
Простите не указал процедуру

--  sp_MoveTablesToFileGroup
--
--  Moves tables, heaps and indexes and LOBS to a filegroup.
--  Author:   Mark White   (maranite@gmail.com)

**Comment by YPermitin** [comment]
@zabavin Можете подробней описать что делаете и для чего.
Не совсем понятен контекст происходящего

**Comment by zabavin** [comment]
День добрый таблицы 3 поля
c_aoguid    uniqueidentifier     
c_houseguid    uniqueidentifier     
fullname    varchar(500)     
 
при перемещении с PRIMARY  в новую. файловую группу 
вызывает неправильное формирование скрипта.
 
У себя я поправил . Просто решил отписать на что наткнулся
 
 
Так же нельзя переносить таблицу если сделать все поля columnstore 
 
С Уважением , Виталий 
Если будут какие либо еще вопросы, пишите рад буду помочь
nтел  8 962 954 61 01
 
  
>Пятница, 2 октября 2020, 11:19 +03:00 от Permitin Yury <notifications@github.com>:
> 
> 
>@zabavin Можете подробней описать что делаете и для чего.
>Не совсем понятен контекст происходящего
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
Vit Zabavin

**Comment by YPermitin** [comment]
@zabavin принято. Спасибо большое за информацию.

Проверю у себя и доработаю скрипты.

**Comment by zabavin** [comment]
Рад помочь.
Есть много интересных наработок . Готов делиться
особенно в часть SQLCLR 
 

  
>Воскресенье, 4 октября 2020, 11:32 +03:00 от Permitin Yury <notifications@github.com>:
> 
> 
>@zabavin принято. Спасибо большое за информацию.
>Проверю у себя и доработаю скрипты.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Vit Zabavin

**Comment by YPermitin** [comment]
@zabavin Если есть желание, то можете прислать информацию. Могу выложить сюда, создав новый раздел "SQLServer-CLR".
Или можете создать свой репозиторий и я добавлю на него ссылку.
