### ISSUE TITLE
Не работает ссылка на статью Алексея Лустина

### ISSUE THREAD

**Issue by yuriybylinkin** [YPermitin/SQLServerTools#25]
На странице https://github.com/YPermitin/SQLServerTools/tree/master/1%D0%A1-Extended-Database-Settings-Maintenance не работает ссылка на статью Алексея Лустина "Про отсутствующие индексы и 1С" (статья удалена)

**Comment by YPermitin** [comment]
@yuriybylinkin да, похоже удалили. И уже давно.

Это случаем не она: https://www.klerk.ru/soft/articles/352141/
Если да, то я обновлю ссылку.

**Comment by YPermitin** [comment]
Обновил ссылку.
