### ISSUE TITLE
Вопрос по инструменту расширенной настройки индексов

### ISSUE THREAD

**Issue by Falra** [YPermitin/SQLServerTools#29]
Зачем после выполнения команды формирования индекса он отключается?

[https://github.com/YPermitin/SQLServerTools/blob/c17308dd274eafe16ed0ee2060349efd9e7b1c7d/1%D0%A1-Extended-Database-Settings-Maintenance/Programmability/Procedures/dbo.CustomSettingsMaintenanceOnTableCreate.sql#L62-L68](url)

Это для ускорения дальнейшей вставки данных? Тогда как он затем включится обратно?
При создании индексов есть проверка на платформенный/неплатформенный индекс, но там разве не нужен ребилд, если результат 1?
[https://github.com/YPermitin/SQLServerTools/blob/master/1%D0%A1-Extended-Database-Settings-Maintenance/Programmability/Procedures/dbo.CustomSettingsMaintenanceOnIndexCreate.sql#L14-L26](url)

В таком случае последовательность все равно не подойдет - индекс создастся, ребилд отработает в рамках команды создания, а потом индекс отключится - во всяком случае на MS SQL 2017 у меня после обновления индекс отключен и с @UnplatformIndex = 0 и @UnplatformIndex = 1

**Comment by Falra** [comment]
А, платформа дважды индексы создает. В таком случае он включится на втором формировании основного индекса.
Я через exec проверял выполнение, поэтому у меня он отключен был

**Comment by YPermitin** [comment]
@Falra доьрого дня.

Как-то упустил сообщение. Хорошо, что разобрались.
+

**Comment by Falra** [comment]
В скриптах ещё имя базы не обёрнуто в [], попалась база с суффиксом “-dev” долго не мог понять почему обновление падает. 
Обертка с Xact abort не помогала
